title: Jason
name: 江松
description: Life is a struggle!
baseurl: 
url: https://www.jasonos.cc

hightlight: true
timezone: Asia/Shanghai

markdown: kramdown
kramdown: 
  input: GFM
  syntax_lighter: rouge